import esbuild from "esbuild";
import fs from "fs/promises";
import process from "process";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "google-drive-sync";

const copyStaticPlugin = {
	name: "copy-static-plugin-files",
	setup(build) {
		build.onEnd(async () => {
			await fs.mkdir(outDir, { recursive: true });
			await Promise.all([
				fs.copyFile(
					"manifest.json",
					path.join(outDir, "manifest.json")
				),
				fs.copyFile("styles.css", path.join(outDir, "styles.css")),
			]);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [copyStaticPlugin],
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
